// Code generated by bpf2go; DO NOT EDIT.
//go:build s390x

package logenricher

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfLogEventT struct {
	_        structs.HostLayout
	Tgid     uint32
	Len      uint32
	Fd       uint32
	Ctx      BpfObiCtxInfoT
	FilePath [64]uint8
	Log      [0]uint8
}

type BpfObiCtxInfoT struct {
	_       structs.HostLayout
	TraceId [16]uint8
	SpanId  [8]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	BpfMapDebugEvents             = "debug_events"
	BpfMapLogEnricherPids         = "log_enricher_pids"
	BpfMapLogEventStorage         = "log_event_storage"
	BpfMapLogEvents               = "log_events"
	BpfMapPathResolverScratch     = "path_resolver_scratch"
	BpfMapPidFd                   = "pid_fd"
	BpfMapTracesCtxV1             = "traces_ctx_v1"
	BpfMapZeros                   = "zeros"
	BpfProgObiKprobeDoWritev      = "obi_kprobe_do_writev"
	BpfProgObiKprobeKsysWrite     = "obi_kprobe_ksys_write"
	BpfProgObiKprobePipeWrite     = "obi_kprobe_pipe_write"
	BpfProgObiKprobeTtyWrite      = "obi_kprobe_tty_write"
	BpfVarG_bpfDebug              = "g_bpf_debug"
	BpfVarG_bpfHeaderPropagation  = "g_bpf_header_propagation"
	BpfVarG_bpfLoopEnabled        = "g_bpf_loop_enabled"
	BpfVarG_bpfTraceparentEnabled = "g_bpf_traceparent_enabled"
	BpfVarLogEventUnused          = "log_event__unused"
)

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	ObiKprobeDoWritev  *ebpf.ProgramSpec `ebpf:"obi_kprobe_do_writev"`
	ObiKprobeKsysWrite *ebpf.ProgramSpec `ebpf:"obi_kprobe_ksys_write"`
	ObiKprobePipeWrite *ebpf.ProgramSpec `ebpf:"obi_kprobe_pipe_write"`
	ObiKprobeTtyWrite  *ebpf.ProgramSpec `ebpf:"obi_kprobe_tty_write"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	DebugEvents         *ebpf.MapSpec `ebpf:"debug_events"`
	LogEnricherPids     *ebpf.MapSpec `ebpf:"log_enricher_pids"`
	LogEventStorage     *ebpf.MapSpec `ebpf:"log_event_storage"`
	LogEvents           *ebpf.MapSpec `ebpf:"log_events"`
	PathResolverScratch *ebpf.MapSpec `ebpf:"path_resolver_scratch"`
	PidFd               *ebpf.MapSpec `ebpf:"pid_fd"`
	TracesCtxV1         *ebpf.MapSpec `ebpf:"traces_ctx_v1"`
	Zeros               *ebpf.MapSpec `ebpf:"zeros"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	G_bpfDebug              *ebpf.VariableSpec `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.VariableSpec `ebpf:"g_bpf_header_propagation"`
	G_bpfLoopEnabled        *ebpf.VariableSpec `ebpf:"g_bpf_loop_enabled"`
	G_bpfTraceparentEnabled *ebpf.VariableSpec `ebpf:"g_bpf_traceparent_enabled"`
	LogEventUnused          *ebpf.VariableSpec `ebpf:"log_event__unused"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	DebugEvents         *ebpf.Map `ebpf:"debug_events"`
	LogEnricherPids     *ebpf.Map `ebpf:"log_enricher_pids"`
	LogEventStorage     *ebpf.Map `ebpf:"log_event_storage"`
	LogEvents           *ebpf.Map `ebpf:"log_events"`
	PathResolverScratch *ebpf.Map `ebpf:"path_resolver_scratch"`
	PidFd               *ebpf.Map `ebpf:"pid_fd"`
	TracesCtxV1         *ebpf.Map `ebpf:"traces_ctx_v1"`
	Zeros               *ebpf.Map `ebpf:"zeros"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.DebugEvents,
		m.LogEnricherPids,
		m.LogEventStorage,
		m.LogEvents,
		m.PathResolverScratch,
		m.PidFd,
		m.TracesCtxV1,
		m.Zeros,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	G_bpfDebug              *ebpf.Variable `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.Variable `ebpf:"g_bpf_header_propagation"`
	G_bpfLoopEnabled        *ebpf.Variable `ebpf:"g_bpf_loop_enabled"`
	G_bpfTraceparentEnabled *ebpf.Variable `ebpf:"g_bpf_traceparent_enabled"`
	LogEventUnused          *ebpf.Variable `ebpf:"log_event__unused"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	ObiKprobeDoWritev  *ebpf.Program `ebpf:"obi_kprobe_do_writev"`
	ObiKprobeKsysWrite *ebpf.Program `ebpf:"obi_kprobe_ksys_write"`
	ObiKprobePipeWrite *ebpf.Program `ebpf:"obi_kprobe_pipe_write"`
	ObiKprobeTtyWrite  *ebpf.Program `ebpf:"obi_kprobe_tty_write"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.ObiKprobeDoWritev,
		p.ObiKprobeKsysWrite,
		p.ObiKprobePipeWrite,
		p.ObiKprobeTtyWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_s390_bpfeb.o
var _BpfBytes []byte
